testing
a
function
that
throw
on
failure