i
have
come
across
the
following
type
of
code
many
a
time
,
and
i
wonder
if
this
is
a
good
practice
(
from
performance
perspective
)
or
not
:
try
{
...
//
some
code
}
catch
(
exception
ex
)
{
...
//
do
something
throw
new
customexception
(
ex
)
;
}
basically
,
what
the
coder
is
doing
is
that
they
are
encompassing
the
exception
in
a
custom
exception
and
throwing
that
again.
how
doe
this
differ
in
performance
from
the
following
two
:
try
{
...
//
some
code
}
catch
(
exception
ex
)
{
..
//
do
something
throw
ex
;
}
or
try
{
...
//
some
code
}
catch
(
exception
ex
)
{
..
//
do
something
throw
;
}
putting
aside
any
functional
or
coding
best
practice
argument
,
is
there
any
performance
difference
between
the
3
approach
?
thanks
.